name: ci / release

on:
  push:
    branches:
      - main
jobs:
  release_please:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
      pull-requests: write

    outputs:
      releases_created: ${{ steps.release_please.outputs.releases_created }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - uses: googleapis/release-please-action@v4
        id: release_please
        with:
          token: ${{ secrets.PAT }}
          config-file: .github/release-config.json
          manifest-file: .github/.release-manifest.json

  build_and_push_release:
    runs-on: ubuntu-latest
    environment: development
    needs: [release_please]
    if: ${{ !cancelled() && !failure() && needs.release_please.outputs.releases_created == 'true' }}

    permissions:
      pull-requests: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: RND.Tools.CmdLine/packages.lock.json
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: dotnet restore --locked-mode

      - name: Build CmdLine
        run: dotnet build --no-restore --configuration Release RND.Tools.CmdLine

      - name: Create the CmdLine package
        run: dotnet pack --no-restore --no-build --configuration Release RND.Tools.CmdLine

      - name: Publish the package to GPR
        run: dotnet nuget push artifacts/package/release/*.nupkg

      - uses: cloudposse-github-actions/get-pr@v2
        id: pr
      - uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue_number: ${{ steps.pr.outputs.number }}
          add: 'autorelease: published'
