name: ci / pr check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - release-*
    paths:
      - '**/*'
      - '!.github/**'
      - '!**/*.md'
      - '!**/docs/**'
      - '!.editorconfig'
      - '!LICENSE'
      - 'README.md'

jobs:
  test_build:
    if: ${{ github.event.pull_request.draft == false && !contains(join(github.event.pull_request.labels.*.name), 'autorelease') }}
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: RND.Tools.CmdLine/packages.lock.json

      - run: dotnet restore --locked-mode
      - name: Create the package
        run: dotnet build --no-restore --configuration Release
