name: ci / pr docks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - release-*
    paths:
      - '.github/**'
      - '**/*.md'
      - '**/docs/**'
      - '.editorconfig'
      - 'LICENSE'

jobs:
  check_changes:
    if: ${{ github.event.pull_request.draft == false && !contains(join(github.event.pull_request.labels.*.name), 'autorelease') }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Checking document's changes"
