name: pm / issues

on:
  issues:
    types: [ assigned, labeled, unlabeled, closed ]
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ opened, reopened, labeled, unlabeled, closed ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
